version: '3.5'
networks:
  testing_env:
    external:
      name: testing_env
services:
  java-pratice:
    image: pratice-app:latest
    hostname: java-pratice
    container_name: java-pratice
    ports:
      - "8085:8080"
    restart: unless-stopped
    networks:
      - testing_env
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/demodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  postgres:
    image: postgres:alpine
    hostname: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - testing_env
    environment:
      - POSTGRES_PASSWORD=password